export { default as AnimationDetailPage } from './AnimationDetailPage';
export { default as AnimationPage } from './AnimationPage';
export { default as AnimationStudioPage } from './AnimationStudioPage';
export { default as AvatarsPage } from './AvatarsPage';
export { default as DashboardPage } from './DashboardPage';
export { default as EmailVerificationPage } from './EmailVerificationPage';
export { default as HomePage } from './HomePage';
export { default as LoginPage } from './LoginPage';
export { default as ProjectPage } from './ProjectPage';
export { default as RegisterPage } from './RegisterPage';
export { default as StoryDetailPage } from './StoryDetailPage';
export { StoryGeneratorPage } from './StoryGeneratorPage'; 